### ISSUE TITLE
Client error '400 Bad Request' for url 'http://192.168.0.226/ISAPI/Event/notification/httpHosts'

### ISSUE THREAD

**Issue by ernestasga** [maciej-or/hikvision_next#128]
Hikvision NVR:        DS-7616NXI-K2
Integration:             v1.0.10

Setup everything correctly, connected but receving error 400

```
homeassistant    | 2023-12-03 15:06:28.707 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Network Video Recorder for hikvision_next
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
homeassistant    |     result = await component.async_setup_entry(hass, self)
homeassistant    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/config/custom_components/hikvision_next/__init__.py", line 75, in async_setup_entry
homeassistant    |     await isapi.set_alarm_server(entry.data[DATA_ALARM_SERVER_HOST], ALARM_SERVER_PATH)
homeassistant    |   File "/config/custom_components/hikvision_next/isapi.py", line 764, in set_alarm_server
homeassistant    |     response = await self.isapi.Event.notification.httpHosts(method=PUT, data=xml)
homeassistant    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
homeassistant    |   File "/usr/local/lib/python3.11/site-packages/hikvisionapi/hikvisionapi.py", line 311, in common_request
homeassistant    |     response.raise_for_status()
homeassistant    |   File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
homeassistant    |     raise HTTPStatusError(message, request=request, response=self)
homeassistant    | httpx.HTTPStatusError: Client error '400 Bad Request' for url 'http://192.168.0.226/ISAPI/Event/notification/httpHosts'
homeassistant    | For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
```

**Comment by ernestasga** [comment]
Yes, unchecking the checkbox solved the problem. Thanks
