### ISSUE TITLE
No Motion Sensor notification for some cameras only

### ISSUE THREAD

**Issue by kingp0dd** [maciej-or/hikvision_next#265]
- Added NVR in hikvision_next
- Cameras were automatically added
- Some cameras don't have Motion Detection

I checked further, the only cameras that have Motion Sensor detected in HASS are:

1. Cameras that have VCA mode "by NVR":

![image](https://github.com/user-attachments/assets/4651e0a2-07d8-4df5-b0d3-1794b2ad5230)

2. Cameras that have VCA mode "by Camera", but specific models only:

```
DS-2CD1047G2-L = VCA mode "by Camera" = with Motion Sensor in HASS
HWI-T240H = VCA mode "by Camera"  = no Motion Sensor in HASS
```

I tried to add `HWI-T240H` in hikvision_next (not through NVR) but there is no motion sensor entity.

`HWI-T240H` supports Motion Detection, and is enabled both in NVR and the Camera's own web UI:
NVR:
![image](https://github.com/user-attachments/assets/7d6add34-9117-44c0-9384-6cfabcc5b521)
Camera:
![image](https://github.com/user-attachments/assets/ef6d1c1a-ca36-44c7-860e-601bcf3ee50f)

**Comment by kingp0dd** [comment]
Update1:

I checked the logs in the NVR and the motion detected notifications were there:

![image](https://github.com/user-attachments/assets/e751974d-a073-40b8-9c9e-31c126dde02f)

However in HASS, the Motion entity is all Clear:

![image](https://github.com/user-attachments/assets/f3111f93-9f97-451d-93ed-ad2a305aab40)

**Comment by kingp0dd** [comment]
> Yea it is know issue, some events are not recognised or are not delivered. The first case I can fix. All I need is log https://github.com/maciej-or/hikvision_next#reporting-issues Enable the log and trigger an event, the most important part starts after --- Incoming event notification --- line. Please paste what you catch.

I seem to be getting only the following:

```

2024-12-03 13:27:31.152 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/1/video/motionDetection
2024-12-03 13:27:31.152 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'false', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcffc080fe0000fe0000fe0000fe0000fe0000'}}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.161 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/2/video/motionDetection
2024-12-03 13:27:31.161 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc', 'RegionList': {'Region': [{'id': '1', 'RegionCoordinatesList': {'RegionCoordinates': [{'positionX': '1', 'positionY': '765'}, {'positionX': '418', 'positionY': '793'}, {'positionX': '816', 'positionY': '6'}, {'positionX': '7', 'positionY': '11'}]}}, {'id': '2', 'RegionCoordinatesList': {'RegionCoordinates': [{'positionX': '347', 'positionY': '974'}, {'positionX': '817', 'positionY': '6'}, {'positionX': '992', 'positionY': '11'}, {'positionX': '986', 'positionY': '540'}, {'positionX': '551', 'positionY': '958'}]}}]}}, 'targetType': 'human,vehicle'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.168 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/3/video/motionDetection
2024-12-03 13:27:31.168 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc', 'RegionList': {'Region': {'id': '1', 'RegionCoordinatesList': {'RegionCoordinates': [{'positionX': '269', 'positionY': '9'}, {'positionX': '509', 'positionY': '972'}, {'positionX': '996', 'positionY': '997'}, {'positionX': '990', 'positionY': '4'}]}}}}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.175 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/4/video/motionDetection
2024-12-03 13:27:31.175 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc', 'RegionList': {'Region': {'id': '1', 'RegionCoordinatesList': {'RegionCoordinates': [{'positionX': '3', 'positionY': '589'}, {'positionX': '773', 'positionY': '470'}, {'positionX': '996', 'positionY': '666'}, {'positionX': '990', 'positionY': '4'}, {'positionX': '0', 'positionY': '2'}]}}}}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.182 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/5/video/motionDetection
2024-12-03 13:27:31.182 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc'}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.191 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/6/video/motionDetection
2024-12-03 13:27:31.191 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'f00000fe0000fe0000fe0000ff0000ff0000ff0000ff0000fc0000fc0000fc0000fc0000fc0000fc0000f40000'}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.201 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/7/video/motionDetection
2024-12-03 13:27:31.201 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc', 'RegionList': {'Region': {'id': '1', 'RegionCoordinatesList': {'RegionCoordinates': [{'positionX': '0', 'positionY': '1000'}, {'positionX': '1000', 'positionY': '1000'}, {'positionX': '1000', 'positionY': '0'}, {'positionX': '0', 'positionY': '0'}]}}}}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.208 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/8/video/motionDetection
2024-12-03 13:27:31.208 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'false', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc'}}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.218 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/9/video/motionDetection
2024-12-03 13:27:31.218 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '40', 'layout': {'gridMap': '0000000000000000007f8000ff8000ffc000ffc000ffe000fff800fffc00ffffe0ffffe0fffff0fffff0fffff0'}}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.224 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/10/video/motionDetection
2024-12-03 13:27:31.224 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'false', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc'}, 'targetType': 'human'}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.233 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/11/video/motionDetection
2024-12-03 13:27:31.233 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc'}}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.241 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/InputProxy/channels/12/video/motionDetection
2024-12-03 13:27:31.241 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'MotionDetection': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'enabled': 'true', 'enableHighlight': 'true', 'samplingInterval': '5', 'startTriggerTime': '1000', 'endTriggerTime': '1000', 'regionType': 'grid', 'Grid': {'rowGranularity': '15', 'columnGranularity': '22'}, 'MotionDetectionLayout': {'@version': '2.0', '@xmlns': 'http://www.isapi.org/ver20/XMLSchema', 'sensitivityLevel': '60', 'layout': {'gridMap': 'fffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffcfffffc'}}, 'maxMegaPixels': '6'}}
2024-12-03 13:27:31.250 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://10.10.20.2/ISAPI/ContentMgmt/Storage
2024-12-03 13:27:31.250 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'storage': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'hddList': {'hdd': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '1', 'hddName': 'hdd1', 'hddPath': None, 'hddType': 'SATA', 'status': 'ok', 'capacity': '3815447', 'freeSpace': '0', 'property': 'RW'}}, 'nasList': None, 'workMode': 'quota'}}
2024-12-03 13:27:31.250 DEBUG (MainThread) [custom_components.hikvision_next.coordinator] Finished fetching hikvision_next data in 0.173 seconds (success: True)
```

The only incoming event notification is from a camera that is already notifying HASS:

```

2024-12-03 13:21:13.903 DEBUG (MainThread) [custom_components.hikvision_next.notifications] --- Incoming event notification ---
2024-12-03 13:21:13.903 DEBUG (MainThread) [custom_components.hikvision_next.notifications] Source: 10.10.20.2
2024-12-03 13:21:13.903 DEBUG (MainThread) [custom_components.hikvision_next.notifications] request headers: <CIMultiDictProxy('Host': '10.10.10.5', 'User-Agent': 'HTTP_USER_AGENT', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'ZH-cn;zh;q=0.5', 'Accept-Charset': 'gb2312,utf8;q=0.7,*;q=0.7', 'Authorization': 'Basic Og==', 'Content-Type': 'application/xml; charset="UTF-8"', 'Content-Length': '599', 'Connection': 'Keep-Alive')>
2024-12-03 13:21:13.904 DEBUG (MainThread) [custom_components.hikvision_next.notifications] alert info: <?xml version="1.0" encoding="UTF-8" ?>
<EventNotificationAlert version="1.0" xmlns="http://www.hikvision.com/ver20/XMLSchema">
<ipAddress>10.10.20.2</ipAddress>
<portNo>80</portNo>
<protocolType>HTTP</protocolType>
<macAddress>dc:07:f8:30:e4:d1</macAddress>
<dynChannelID>6</dynChannelID>
<channelID>6</channelID>
<dateTime>2024-12-03T13:21:12+08:00</dateTime>
<activePostCount>0</activePostCount>
<eventType>VMD</eventType>
<eventState>active</eventState>
<eventDescription>Motion alarm</eventDescription>
<channelName>Garage</channelName>
<targetType>human</targetType>
</EventNotificationAlert>

2024-12-03 13:21:13.904 DEBUG (MainThread) [custom_components.hikvision_next.notifications] Alert: AlertInfo(channel_id=6, io_port_id=0, event_id='motiondetection', device_serial_no=None, mac='dc:07:f8:30:e4:d1', region_id=0, detection_target=None)
2024-12-03 13:21:13.904 DEBUG (MainThread) [custom_components.hikvision_next.notifications] UNIQUE_ID: binary_sensor.ds_7616ni_q21620240426ccrrfd5181731wcvu_6_motiondetection
```

I am also seeing the following repeated every second, not sure if related:

```
2024-12-03 13:21:16.039 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'#'
      ^
```

**Comment by sp6vxh** [comment]
HA via HTTPS - the recorder does not accept an HA address.

recorder: DS-7616NXI-K2, firmware V4.82.100 build 240606, hardware version B-R-K20A9_K20A9-00, web add-on version V4.0.1 build 240514, add-on version 4.0.0.3

When adding new hardware to NEXT, the HA address entered is https://192/......, the HOST address displayed by NEXT is 0.0.0.0, the host protocol is HTTP, the host port is 80. After entering the HA address http://192 /..... all values ​​returned by NEXT are valid.

After disabling the HTTPS protocol for HA (needed for external access using DuckDNS), communication between the registrar and HA using HTTP is correct.

Some cameras can communicate with HA via HTTPS:
DS-2CD2343G2-I firmware V5.7.14 build 231213 (in this camera you can set the address and protocol locally and remotely in the network/advanced/alarm server section);

**Comment by kingp0dd** [comment]
Got it thanks! Is there a way to disable the notification (to prevent
flooding in HASS Logs) but still enable the camera entity to allow me to
continue viewing the camera feed in HASS?

**Comment by maciej-or** [comment]
you can disable Notify Surveillance Center but unfortunately it disables notification in hik-connect as well

**Comment by kingp0dd** [comment]
Got it thank you mate!
