### ISSUE TITLE
V1.1.0 Migration Error

### ISSUE THREAD

**Issue by open1999** [maciej-or/hikvision_next#266]
Hello,

I updated to v1.1.0.
HA V 2024.11.3

I have an migration error

`Enregistreur: homeassistant.config_entries
Source: config_entries.py:978
S'est produit pour la première fois: 18:19:22 (1 occurrences)
Dernier enregistrement: 18:19:22

Error migrating entry CAM1 for hikvision_next
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/__init__.py", line 139, in async_migrate_entry
    entity_registry.async_remove(entity_id)
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/entity_registry.py", line 934, in async_remove
    entity = self.entities.pop(entity_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 945, in pop
  File "/usr/local/lib/python3.12/collections/__init__.py", line 1135, in __getitem__
    raise KeyError(key)
KeyError: 'sensor._alarm_server_protocoltype'`

**Comment by maciej-or** [comment]
If the integration works you can ignore that, if not let me know.

**Comment by open1999** [comment]
unfortunately the addon does not work and the integration indicates to look at the log.

I downgraded to v1.0.19

**Comment by solankiS** [comment]
+1 I'm getting the same error

Core version - 2024.11.3
Supervisor version - 2024.11.4
Operating System - 3.2
Frontend - 20241106.2

Error message 

2024-11-29 08:22:57.694 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry NVR for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/__init__.py", line 139, in async_migrate_entry
    entity_registry.async_remove(entity_id)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 934, in async_remove
    entity = self.entities.pop(entity_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by rickyrickuk** [comment]
Same here.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/__init__.py", line 139, in async_migrate_entry
    entity_registry.async_remove(entity_id)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 934, in async_remove
    entity = self.entities.pop(entity_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 945, in pop
  File "/usr/local/lib/python3.12/collections/__init__.py", line 1135, in __getitem__
    raise KeyError(key)
KeyError: 'sensor._alarm_server_protocoltype

**Comment by maciej-or** [comment]
use dev branch https://github.com/maciej-or/hikvision_next/tree/dev until next release

**Comment by solankiS** [comment]
> use dev branch https://github.com/maciej-or/hikvision_next/tree/dev until next release

I was unable to download the dev from HACs so I have rolled back.
