### ISSUE TITLE
Latest update V1.1.0 broke my camera integration and now it reports back error's 

### ISSUE THREAD

**Issue by Sweepr** [maciej-or/hikvision_next#268]
Latest update V1.1.0 broke my camera integration and now it reports back error's 

![image](https://github.com/user-attachments/assets/aebba8a5-677f-43d9-a364-6aa574dec8b3)

This entity is no longer being provided by the hikvision_next integration. If the entity is no longer in use, delete it in settings.

Hikvision NVR / IP Camera update
7 minutes ago
Up-to-date
Installed version
v1.1.0
Latest version
v1.1.0

How to recover?

`Logger: homeassistant.setup
Source: loader.py:821
First occurred: 14:16:30 (1 occurrences)
Last logged: 14:16:30

Setup failed for custom integration hikvision_next: Unable to import component: Exception importing custom_components.hikvision_next
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/volume1/@appdata/homeassistant/config/custom_components/hikvision_next/__init__.py", line 37
    type HikvisionConfigEntry = ConfigEntry[HikvisionDevice]
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/loader.py", line 821, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.hikvision_next
`

`Logger: homeassistant.loader
Source: loader.py:813
First occurred: 14:16:30 (1 occurrences)
Last logged: 14:16:30

Unexpected exception importing component custom_components.hikvision_next
Traceback (most recent call last):
  File "/volume1/@appstore/homeassistant/env/lib/python3.11/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/volume1/@appdata/homeassistant/config/custom_components/hikvision_next/__init__.py", line 37
    type HikvisionConfigEntry = ConfigEntry[HikvisionDevice]
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
`

**Comment by maciej-or** [comment]
use dev branch https://github.com/maciej-or/hikvision_next/tree/dev until next release
