### ISSUE TITLE
Error: object of type 'NoneType'

### ISSUE THREAD

**Issue by b383rt** [maciej-or/hikvision_next#282]
Hello,

I need some assistance with an integration issue. I am using Home Assistant OS and trying to integrate my Hikvision camera, model DS-2CD2046G2-I (which is not listed among the tested cameras). I have enabled the "Hikvision-CGI" option and have tried connecting using both the admin account and another user with the correct permissions enabled. I have also tried both HTTP and HTTPS.

However, I am still encountering the same issue: Error: "Cannot initialize hikvision_next http://192.168.1.53. Error: object of type 'NoneType' has no len() Traceback"

You will find the full log below

I would greatly appreciate any help or advice on how to resolve this issue.

Thank you in advance for your support!

Best regards,
Bertrand

---------------------------------------------------------
2024-12-29 11:58:47.903 INFO (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://192.168.1.53/ISAPI/Event/triggers
Server error '500 Internal Server Error' for url 'https://192.168.1.53/ISAPI/Event/triggers'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2024-12-29 11:58:47.966 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] --- [GET] https://192.168.1.53/ISAPI/Event/triggers/scenechangedetection-1
2024-12-29 11:58:47.966 DEBUG (MainThread) [custom_components.hikvision_next.isapi.isapi] 
{'EventTrigger': {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': ['scenechangedetection-1', 'scenechangedetection-1'], 'eventType': ['scenechangedetection', 'scenechangedetection-1'], 'eventDescription': ['scenechangedetection Event trigger Information', 'exception Information'], 'videoInputChannelID': '1', 'dynVideoInputChannelID': '1', 'EventTriggerNotificationList': {'EventTriggerNotification': [{'id': 'record-1', 'notificationMethod': 'record', 'videoInputID': '1', 'notificationRecurrence': 'beginning'}, {'id': 'center', 'notificationMethod': 'center', 'notificationRecurrence': 'beginning'}, {'id': 'FTP', 'notificationMethod': 'FTP', 'notificationRecurrence': 'beginning'}]}}}
**2024-12-29 11:58:47.970 ERROR (MainThread) [custom_components.hikvision_next] Cannot initialize hikvision_next** https://192.168.1.53. Error: 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/config/custom_components/hikvision_next/__init__.py", line 53, in async_setup_entry
    await device.get_hardware_info()
  File "/config/custom_components/hikvision_next/isapi/isapi.py", line 124, in get_hardware_info
    self.supported_events = await self.get_supported_events(capabilities)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/isapi/isapi.py", line 306, in get_supported_events
    if event := create_event_info(event_trigger):
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/config/custom_components/hikvision_next/isapi/isapi.py", line 248, in create_event_info
    event_id = event_type.lower()
               ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'lower'
---------------------------------------------------------

**Comment by maciej-or** [comment]
Hi Bertrand,
Your device doesn't respond normally but it can be fixed more wondering are responses 500. Is your firmware up to date?

**Comment by b383rt** [comment]
Hi, 
Indeed my firmware was too old (5.5.131_200220). I updated it to the latest firmware (V5.5.820_231108), and now everything works perfectly ! Thank you so much for your help and your great work !
