### ISSUE TITLE
BUG: Crash on setup with NVR DS-7608NI-I2

### ISSUE THREAD

**Issue by mion00** [maciej-or/hikvision_next#3]
I am trying to add the NVR `DS-7608NI-I2`, but it seems that if fails to decode its serial number?
There are 7 Hikvision cameras attached to it.

Exception details:
```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
    await isapi.get_nvr_capabilities()
  File "/config/custom_components/hikvision_next/isapi.py", line 108, in get_nvr_capabilities
    channel_info = self.get_nvr_channel_device_info(channel)
  File "/config/custom_components/hikvision_next/isapi.py", line 87, in get_nvr_channel_device_info
    serial_number = channel_descriptor["serialNumber"]
KeyError: 'serialNumber'
```

Full logs:
```
2023-02-26 11:21:22.807 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.0.240/ISAPI/System/deviceInfo {'DeviceInfo': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'deviceName': 'Network Video Recorder', 'deviceID': '484a3238-3932-3138-3731-240f9b0f655a', 'model': 'DS-7608NI-I2', 'serialNumber': 'DS-7608NI-I20820211224CCRRJ28921871WCVU', 'macAddress': '24:0f:9b:0f:65:5a', 'firmwareVersion': 'V4.31.108', 'firmwareReleasedDate': 'build 210823', 'encoderVersion': 'V5.0', 'encoderReleasedDate': 'build 210818', 'deviceType': 'NVR', 'telecontrolID': '255', 'manufacturer': 'hikvision'}}
2023-02-26 11:21:22.882 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.0.240/ISAPI/ContentMgmt/InputProxy/channels {'InputProxyChannelList': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', '@size': '0', 'InputProxyChannel': [{'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '1', 'name': 'LATO NORD', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.241', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '7a82c27d-7152-4f31-9d36-a4d707ef7522'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '2', 'name': 'Piazzale', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.243', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'ba335f61-9252-4783-b8dd-743505984f5e'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '3', 'name': 'Cancello', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.242', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '20073332-4b5a-4c0f-a428-b2ea22092c4c'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '4', 'name': 'Orto', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.244', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'afd3255b-71a0-4297-889f-a0199ac5f248'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '5', 'name': 'IPCamera 05', 'sourceInputPortDescriptor': {'proxyProtocol': 'ONVIF', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.8', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableTiming': 'true'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '6', 'name': 'Camera 01', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.234', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableTiming': 'true', 'devIndex': '49ec300f-fea1-493f-8ada-dcddee792eab'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '7', 'name': 'LATO SUD', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.245', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'acdaa52d-5784-405b-846b-272f434ed139'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '8', 'name': 'RETRO CAPANNONI', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.246', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '7baadb03-076e-4be9-a575-35f9351f8825'}]}}
2023-02-26 11:21:22.883 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception Cannot initialize hikvision_next 'serialNumber'
2023-02-26 11:21:22.884 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Network Video Recorder for hikvision_next
File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
File "/config/custom_components/hikvision_next/isapi.py", line 108, in get_nvr_capabilities
File "/config/custom_components/hikvision_next/isapi.py", line 87, in get_nvr_channel_device_info
2023-02-26 11:23:09.390 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.0.240/ISAPI/System/deviceInfo {'DeviceInfo': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'deviceName': 'Network Video Recorder', 'deviceID': '484a3238-3932-3138-3731-240f9b0f655a', 'model': 'DS-7608NI-I2', 'serialNumber': 'DS-7608NI-I20820211224CCRRJ28921871WCVU', 'macAddress': '24:0f:9b:0f:65:5a', 'firmwareVersion': 'V4.31.108', 'firmwareReleasedDate': 'build 210823', 'encoderVersion': 'V5.0', 'encoderReleasedDate': 'build 210818', 'deviceType': 'NVR', 'telecontrolID': '255', 'manufacturer': 'hikvision'}}
2023-02-26 11:23:09.543 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.0.240/ISAPI/ContentMgmt/InputProxy/channels {'InputProxyChannelList': {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', '@size': '0', 'InputProxyChannel': [{'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '1', 'name': 'LATO NORD', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.241', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '7a82c27d-7152-4f31-9d36-a4d707ef7522'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '2', 'name': 'Piazzale', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.243', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'ba335f61-9252-4783-b8dd-743505984f5e'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '3', 'name': 'Cancello', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.242', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '20073332-4b5a-4c0f-a428-b2ea22092c4c'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '4', 'name': 'Orto', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.244', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'afd3255b-71a0-4297-889f-a0199ac5f248'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '5', 'name': 'IPCamera 05', 'sourceInputPortDescriptor': {'proxyProtocol': 'ONVIF', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.8', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableTiming': 'true'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '6', 'name': 'Camera 01', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.234', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableTiming': 'true', 'devIndex': '49ec300f-fea1-493f-8ada-dcddee792eab'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '7', 'name': 'LATO SUD', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.245', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': 'acdaa52d-5784-405b-846b-272f434ed139'}, {'@version': '1.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '8', 'name': 'RETRO CAPANNONI', 'sourceInputPortDescriptor': {'proxyProtocol': 'HIKVISION', 'addressingFormatType': 'ipaddress', 'ipAddress': '192.168.0.246', 'managePortNo': '8000', 'srcInputPort': '1', 'userName': 'admin', 'streamType': 'auto', 'deviceID': None}, 'enableAnr': 'false', 'enableTiming': 'true', 'devIndex': '7baadb03-076e-4be9-a575-35f9351f8825'}]}}
2023-02-26 11:23:09.543 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception Cannot initialize hikvision_next 'serialNumber'
2023-02-26 11:23:09.544 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Network Video Recorder for hikvision_next
File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
File "/config/custom_components/hikvision_next/isapi.py", line 108, in get_nvr_capabilities
File "/config/custom_components/hikvision_next/isapi.py", line 87, in get_nvr_channel_device_info
```

**Comment by maciej-or** [comment]
It's related to camera (NVR chanel) serial number. It can be missed if device is offline, but I assume your cameras are online. I've checked ISAPI docs as well and **serialNumber** is marked as optional so I added **devIndex** as substitute for serial. I hope it will help.

**Comment by mion00** [comment]
Thanks for the quick reply! :+1: 
Now it seems another field creates problems:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
    await isapi.get_nvr_capabilities()
  File "/config/custom_components/hikvision_next/isapi.py", line 110, in get_nvr_capabilities
    channel_info = self.get_nvr_channel_device_info(channel)
  File "/config/custom_components/hikvision_next/isapi.py", line 95, in get_nvr_channel_device_info
    model=channel_descriptor["model"],
KeyError: 'model'
```

**Comment by maciej-or** [comment]
ok, in time, I still have IDE opened :) pushed another commit into 
https://github.com/maciej-or/hikvision_next/tree/fix/missing_channel_serial_no
it seems your cameras don't provide model and firmware version so you'll see "?" instead of them in HA device page

**Comment by mion00** [comment]
Another commit, another error! :wink: 

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 56, in async_setup_entry
    await isapi.set_alarm_server(
  File "/config/custom_components/hikvision_next/isapi.py", line 305, in set_alarm_server
    and host["ipAddress"] == address.hostname
KeyError: 'ipAddress'
```
[home-assistant_2023-02-26T18-07-55.880Z.log](https://github.com/maciej-or/hikvision_next/files/10834372/home-assistant_2023-02-26T18-07-55.880Z.log)

**Comment by maciej-or** [comment]
good catch, pls uncheck in integration config:
'Set alarm server using following address'
for now and try setup alarm server through NVR interface, I will mange that later on

**Comment by mion00** [comment]
Ok, disabling that option allow to complete the setup. The NVR and the camera are added.
From a quick test I am missing the motion detection events, but I have to re-check the settings first.

**Comment by maciej-or** [comment]
please check dev branch with all fixes
https://github.com/maciej-or/hikvision_next/tree/dev
I recommend remove device from HA, copy new integration version and add device again.

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/releases/tag/v1.0.1
