### ISSUE TITLE
Unable to add DS-7608NI-I2/8P - error about audio

### ISSUE THREAD

**Issue by rickyrickuk** [maciej-or/hikvision_next#44]
When trying to add the NVR, I get the following error in the log 👍 

_2023-05-26 09:18:39.641 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception | Cannot initialize hikvision_next | 'Audio'
2023-05-26 09:18:39.646 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry NVR for hikvision_next
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/config/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
    await isapi.get_nvr_capabilities()
  File "/config/custom_components/hikvision_next/isapi.py", line 199, in get_nvr_capabilities
    streams += self.get_channel_streams(
  File "/config/custom_components/hikvision_next/isapi.py", line 170, in get_channel_streams
    audio=str_to_bool(channel["Audio"]["enabled"]),
KeyError: 'Audio'_

I do get a device in HA, and it identifies the Model and firmware, but no entities are created.

Any help please?

**Comment by rickyrickuk** [comment]
I checked all the pre-reqs and even gave full rights to the account to make sure it wasn't a rights issue but same issue.

**Comment by maciej-or** [comment]
It is a bug from newly added streams feature. Thanks for catching, will fix soon

**Comment by rickyrickuk** [comment]
> It is a bug from newly added streams feature. Thanks for catching, will fix soon

Great, thanks :-)

**Comment by rickyrickuk** [comment]
Thanks for the quick fix, working perfectly now.
