### ISSUE TITLE
Please add compatibility to model DS-7108NI-Q1/8P

### ISSUE THREAD

**Issue by demonio669** [maciej-or/hikvision_next#46]
I try to configure this module to my DS-7108NI-Q1/8P but it gives me the following error:

I think it is similar to bug  #44  ( https://github.com/maciej-or/hikvision_next/issues/44 )

2023-05-26 12:54:42.494 INFO (MainThread) [custom_components.hacs] <Integration maciej-or/hikvision_next> Post installation steps completed
2023-05-26 12:55:15.379 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 200 OK"
2023-05-26 12:55:15.443 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 401 Unauthorized"
2023-05-26 12:55:15.684 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 200 OK"
2023-05-26 12:55:15.752 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/deviceInfo "HTTP/1.1 200 OK"
2023-05-26 12:55:15.753 INFO (MainThread) [homeassistant.setup] Setting up hikvision_next
2023-05-26 12:55:15.753 INFO (MainThread) [homeassistant.setup] Setup of domain hikvision_next took 0.0 seconds
2023-05-26 12:55:15.822 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 200 OK"
2023-05-26 12:55:15.885 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 401 Unauthorized"
2023-05-26 12:55:15.895 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/status "HTTP/1.1 200 OK"
2023-05-26 12:55:15.964 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/System/deviceInfo "HTTP/1.1 200 OK"
2023-05-26 12:55:16.034 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/Streaming/channels "HTTP/1.1 200 OK"
2023-05-26 12:55:16.104 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/ContentMgmt/InputProxy/channels "HTTP/1.1 200 OK"
2023-05-26 12:55:16.175 INFO (MainThread) [httpx] HTTP Request: GET http://192.168.1.190/ISAPI/Event/channels/1/capabilities "HTTP/1.1 200 OK"
2023-05-26 12:55:16.176 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception | Cannot initialize hikvision_next | 'Audio'
2023-05-26 12:55:16.177 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Network Video Recorder for hikvision_next
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/root/.homeassistant/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/root/.homeassistant/custom_components/hikvision_next/__init__.py", line 43, in async_setup_entry
    await isapi.get_nvr_capabilities()
  File "/root/.homeassistant/custom_components/hikvision_next/isapi.py", line 199, in get_nvr_capabilities
    streams += self.get_channel_streams(
  File "/root/.homeassistant/custom_components/hikvision_next/isapi.py", line 170, in get_channel_streams
    audio=str_to_bool(channel["Audio"]["enabled"]),
KeyError: 'Audio'

**Comment by maciej-or** [comment]
https://github.com/maciej-or/hikvision_next/pull/49
