### ISSUE TITLE
DS-2CD2155FWD v1.0.4

### ISSUE THREAD

**Issue by open1999** [maciej-or/hikvision_next#47]
Hello,

DS-2CD2155FWD is ok with v1.0.3, but is not ok with v1.0.4.

Below the debug log with v1.0.4

Regards

`2023-05-27 20:36:33.283 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.X.XXX/ISAPI/System/deviceInfo {'DeviceInfo': {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'deviceName': 'CAM1', 'deviceID': '965dc000-aa09-11b4-833e-xxxxx', 'deviceDescription': 'IPCamera', 'deviceLocation': 'hangzhou', 'systemContact': 'Hikvision.China', 'model': 'DS-2CD2155FWD-I', 'serialNumber': 'DS-2CD2155FWD-SXX', 'macAddress': '4c:bd:8f:xx:xx:xx', 'firmwareVersion': 'V5.6.820', 'firmwareReleasedDate': 'build 220519', 'encoderVersion': 'V7.3', 'encoderReleasedDate': 'build 220307', 'bootVersion': 'V1.3.4', 'bootReleasedDate': '100316', 'hardwareVersion': '0x0', 'deviceType': 'IPCamera', 'telecontrolID': '1', 'supportBeep': 'false', 'supportVideoLoss': 'false', 'firmwareVersionInfo': 'B-R-G1-0'}}

2023-05-27 20:36:33.548 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.X.XXX/ISAPI/Event/capabilities {'EventCap': {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'isSupportHDFull': 'true', 'isSupportHDError': 'true', 'isSupportNicBroken': 'true', 'isSupportIpConflict': 'true', 'isSupportIllAccess': 'true', 'isSupportViException': 'false', 'isSupportViMismatch': 'false', 'isSupportRecordException': 'false', 'isSupportTriggerFocus': 'false', 'isSupportMotionDetection': 'true', 'isSupportVideoLoss': 'false', 'isSupportTamperDetection': 'true', 'isSupportPersonQueueDetection': 'false', 'isSupportTeacherBehaviorDetect': 'false', 'isSupportFaceSnap': 'false', 'isSupportCityManagement': 'false', 'isSupportMixedTargetDetection': 'false'}}

2023-05-27 20:36:33.791 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.X.XXX/ISAPI/Smart/capabilities {'SmartCap': {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'isSupportROI': 'false', 'isSupportFaceDetect': 'false', 'isSupportIntelliTrace': 'false', 'isSupportFieldDetection': 'true', 'isSupportDefocusDetection': 'false', 'isSupportAudioDetection': 'false', 'isSupportSceneChangeDetection': 'true', 'isSupportLineDetection': 'true', 'isSupportRegionEntrance': 'false', 'isSupportRegionExiting': 'false', 'isSupportLoitering': 'false', 'isSupportGroup': 'false', 'isSupportRapidMove': 'false', 'isSupportParking': 'false', 'isSupportUnattendedBaggage': 'false', 'isSupportAttendedBaggage': 'false', 'isSupportPeopleDetection': 'false', 'isSupportSmartCalibration': 'true', 'isSupportStorageDetection': 'false'}}

2023-05-27 20:36:34.071 DEBUG (MainThread) [custom_components.hikvision_next.isapi] http://192.168.X.XXX/ISAPI/Streaming/channels {'StreamingChannelList': {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'StreamingChannel': [{'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '101', 'channelName': 'Front', 'enabled': 'true', 'Transport': {'maxPacketSize': '1000', 'ControlProtocolList': {'ControlProtocol': [{'streamingTransport': 'RTSP'}, {'streamingTransport': 'HTTP'}, {'streamingTransport': 'SHTTP'}]}, 'Unicast': {'enabled': 'true', 'rtpTransportType': 'RTP/TCP'}, 'Multicast': {'enabled': 'true', 'destIPAddress': '0.0.0.0', 'videoDestPortNo': '8860', 'audioDestPortNo': '8862', 'FecInfo': {'fecRatio': '0', 'fecDestPortNo': '8960'}}, 'Security': {'enabled': 'true', 'certificateType': 'digest'}}, 'Video': {'enabled': 'true', 'videoInputChannelID': '1', 'videoCodecType': 'H.265', 'videoScanType': 'progressive', 'videoResolutionWidth': '2560', 'videoResolutionHeight': '1440', 'videoQualityControlType': 'VBR', 'constantBitRate': '8192', 'fixedQuality': '80', 'vbrUpperCap': '8192', 'vbrLowerCap': '32', 'maxFrameRate': '2500', 'keyFrameInterval': '2000', 'snapShotImageType': 'JPEG', 'GovLength': '50', 'SVC': {'enabled': 'false'}, 'PacketType': ['PS', 'RTP'], 'smoothing': '50', 'H265Profile': 'Main', 'SmartCodec': {'enabled': 'true'}, 'vbrAverageCap': '4096'}}, {'@version': '2.0', '@xmlns': 'http://www.hikvision.com/ver20/XMLSchema', 'id': '102', 'channelName': 'Front', 'enabled': 'true', 'Transport': {'maxPacketSize': '1000', 'ControlProtocolList': {'ControlProtocol': [{'streamingTransport': 'RTSP'}, {'streamingTransport': 'HTTP'}, {'streamingTransport': 'SHTTP'}]}, 'Unicast': {'enabled': 'true', 'rtpTransportType': 'RTP/TCP'}, 'Multicast': {'enabled': 'true', 'destIPAddress': '0.0.0.0', 'videoDestPortNo': '8866', 'audioDestPortNo': '8868', 'FecInfo': {'fecRatio': '0', 'fecDestPortNo': '8966'}}, 'Security': {'enabled': 'true', 'certificateType': 'digest'}}, 'Video': {'enabled': 'true', 'videoInputChannelID': '1', 'videoCodecType': 'H.265', 'videoScanType': 'progressive', 'videoResolutionWidth': '640', 'videoResolutionHeight': '480', 'videoQualityControlType': 'VBR', 'constantBitRate': '256', 'fixedQuality': '60', 'vbrUpperCap': '256', 'vbrLowerCap': '32', 'maxFrameRate': '1000', 'keyFrameInterval': '4000', 'snapShotImageType': 'JPEG', 'GovLength': '40', 'SVC': {'enabled': 'false'}, 'PacketType': ['PS', 'RTP'], 'smoothing': '50', 'H265Profile': 'Main'}}]}}

2023-05-27 20:36:34.073 WARNING (MainThread) [custom_components.hikvision_next.isapi] Unexpected exception | Cannot initialize hikvision_next | 'Audio'
2023-05-27 20:36:34.089 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry CAM1 for hikvision_next
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hikvision_next/__init__.py", line 48, in async_setup_entry
    raise ex
  File "/config/custom_components/hikvision_next/__init__.py", line 45, in async_setup_entry
    await isapi.get_ip_camera_capabilities()
  File "/config/custom_components/hikvision_next/isapi.py", line 252, in get_ip_camera_capabilities
    self.streams_info = self.get_channel_streams(self.device_info, "1", stream_list)
  File "/config/custom_components/hikvision_next/isapi.py", line 170, in get_channel_streams
    audio=str_to_bool(channel["Audio"]["enabled"]),
KeyError: 'Audio'`

**Comment by maciej-or** [comment]
duplicates https://github.com/maciej-or/hikvision_next/issues/44

**Comment by open1999** [comment]
ok
Thanks
