### ISSUE TITLE
Camera stream issues

### ISSUE THREAD

**Issue by simonbuerger** [maciej-or/hikvision_next#80]
Thanks for this amazing integration!

With the camera streams themselves I'm getting the following errors in the debug logs and the streams never start (although there is always an up to date still frame in the preview):

```
Logger: root
Source: components/stream/worker.py:264
First occurred: 3 July 2023 at 23:10:43 (19 occurrences)
Last logged: 14:14:04

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/homeassistant/homeassistant/components/stream/__init__.py", line 424, in _run_worker
    stream_worker(
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 611, in stream_worker
    muxer.mux_packet(first_keyframe)
  File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 264, in mux_packet
    self._av_output.mux(packet)
  File "av/container/output.pyx", line 212, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 218, in av.container.output.OutputContainer.mux_one
  File "av/container/output.pyx", line 184, in av.container.output.OutputContainer.start_encoding
  File "av/container/core.pyx", line 292, in av.container.core.Container.err_check
  File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: '<none>'; last error log: [mp4] dimensions not set
```

And
```
Logger: homeassistant.components.stream.stream.camera.ds_7608ni_k20820221221ccrrl10882931wcvu_102
Source: components/stream/__init__.py:434
Integration: Stream (documentation, issues)
First occurred: 3 July 2023 at 23:10:28 (46 occurrences)
Last logged: 14:11:14

Error from stream worker: No dts in 7 consecutive packets
```

Is there any particular video output format config I should be setting on the cameras? The camera showing the DTS error is set the H264 and the ones showing the [mp4] dimensions not set are set to H265, if that helps.

**Comment by simonbuerger** [comment]
Turns out this was due to the encryption key set up on the NVR under Network > Advanced Settings > Platform Access

 I don't know how important this feature is, I've turned mine off for now. Wondering how easy it would be for this integration to support it?

**Comment by maciej-or** [comment]
I'm afraid stream encryption can be handled only by Hik-Connect and other Hik apps. Custom RTSP stream processing is out of scope this integration.

**Comment by simonbuerger** [comment]
Ok closing this then, thanks!
